
spring.application.name=budget-advisor

spring.datasource.url=jdbc:mysql://localhost:3306/student_budget
spring.datasource.username=root
spring.datasource.password=216CI119@ar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080